//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
  providedIn: 'root'
})

export class LicenseClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
    this.http = http;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
  }

  generateLicense(): Observable<void> {
    let url_ = this.baseUrl + "/api/License";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Accept": "application/json"
      })
    };

    return this.http.request("post", url_, options_).pipe(_observableMergeMap((response_: any) => {
      return this.processGenerateLicense(response_);
    })).pipe(_observableCatch((response_: any) => {
      if (response_ instanceof HttpResponseBase) {
        try {
          return this.processGenerateLicense(response_ as any);
        } catch (e) {
          return _observableThrow(e) as any as Observable<void>;
        }
      } else
        return _observableThrow(response_) as any as Observable<void>;
    }));
  }

  protected processGenerateLicense(response: HttpResponseBase): Observable<void> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse ? response.body :
        (response as any).error instanceof Blob ? (response as any).error : undefined;

    let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
    if (status === 200) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        let result200: any = null;
        return _observableOf(result200);
      }));
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      }));
    }
    return _observableOf(null as any);
  }

  getLatestLicense(): Observable<string> {
    let url_ = this.baseUrl + "/api/License";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Accept": "application/json"
      })
    };

    return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
      return this.processGetLatestLicense(response_);
    })).pipe(_observableCatch((response_: any) => {
      if (response_ instanceof HttpResponseBase) {
        try {
          return this.processGetLatestLicense(response_ as any);
        } catch (e) {
          return _observableThrow(e) as any as Observable<string>;
        }
      } else
        return _observableThrow(response_) as any as Observable<string>;
    }));
    }

  protected processGetLatestLicense(response: HttpResponseBase): Observable<string> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse ? response.body :
        (response as any).error instanceof Blob ? (response as any).error : undefined;

    let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
    if (status === 200) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        let result200 = _responseText === "" ? null : _responseText;
        return _observableOf(result200);
      }));
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      }));
    }
    return _observableOf(null as any);
  }
}

@Injectable({
  providedIn: 'root'
})

export class SearchEngineClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

  constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
    this.http = http;
    this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
  }

  getDataFileUsingSearchEngine(searchString: string | null | undefined): Observable<DataFileDto> {
    let url_ = this.baseUrl + "/api/SearchEngine?";
    if (searchString !== undefined && searchString !== null)
      url_ += "SearchString=" + encodeURIComponent("" + searchString) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Accept": "application/json"
      })
    };

    return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_: any) => {
      return this.processGetDataFileUsingSearchEngine(response_);
    })).pipe(_observableCatch((response_: any) => {
      if (response_ instanceof HttpResponseBase) {
        try {
          return this.processGetDataFileUsingSearchEngine(response_ as any);
        } catch (e) {
          return _observableThrow(e) as any as Observable<DataFileDto>;
        }
      } else
        return _observableThrow(response_) as any as Observable<DataFileDto>;
    }));
  }

  protected processGetDataFileUsingSearchEngine(response: HttpResponseBase): Observable<DataFileDto> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse ? response.body :
        (response as any).error instanceof Blob ? (response as any).error : undefined;

    let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
    if (status === 200) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        let result200: any = null;
        let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = DataFileDto.fromJS(resultData200);
        return _observableOf(result200);
      }));
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
      }));
    }
    return _observableOf(null as any);
  }
}

export class DataFileDto implements IDataFileDto {
  buildings?: BuildingDto[] | undefined;
  groups?: GroupDto[] | undefined;
  locks?: LockDto[] | undefined;
  media?: MediaDto[] | undefined;

  constructor(data?: IDataFileDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      if (Array.isArray(_data["buildings"])) {
        this.buildings = [] as any;
        for (let item of _data["buildings"])
          this.buildings!.push(BuildingDto.fromJS(item));
      }
      if (Array.isArray(_data["groups"])) {
        this.groups = [] as any;
        for (let item of _data["groups"])
          this.groups!.push(GroupDto.fromJS(item));
      }
      if (Array.isArray(_data["locks"])) {
        this.locks = [] as any;
        for (let item of _data["locks"])
          this.locks!.push(LockDto.fromJS(item));
      }
      if (Array.isArray(_data["media"])) {
        this.media = [] as any;
        for (let item of _data["media"])
          this.media!.push(MediaDto.fromJS(item));
      }
    }
  }

  static fromJS(data: any): DataFileDto {
    data = typeof data === 'object' ? data : {};
    let result = new DataFileDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    if (Array.isArray(this.buildings)) {
      data["buildings"] = [];
      for (let item of this.buildings)
        data["buildings"].push(item.toJSON());
    }
    if (Array.isArray(this.groups)) {
      data["groups"] = [];
      for (let item of this.groups)
        data["groups"].push(item.toJSON());
    }
    if (Array.isArray(this.locks)) {
      data["locks"] = [];
      for (let item of this.locks)
        data["locks"].push(item.toJSON());
    }
    if (Array.isArray(this.media)) {
      data["media"] = [];
      for (let item of this.media)
        data["media"].push(item.toJSON());
    }
    return data;
  }
}

export interface IDataFileDto {
  buildings?: BuildingDto[] | undefined;
  groups?: GroupDto[] | undefined;
  locks?: LockDto[] | undefined;
  media?: MediaDto[] | undefined;
}

export class BuildingDto implements IBuildingDto {
  id?: string;
  description?: string | undefined;
  shortCut?: string | undefined;
  name?: string | undefined;

  constructor(data?: IBuildingDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.description = _data["description"];
      this.shortCut = _data["shortCut"];
      this.name = _data["name"];
    }
  }

  static fromJS(data: any): BuildingDto {
    data = typeof data === 'object' ? data : {};
    let result = new BuildingDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    data["id"] = this.id;
    data["description"] = this.description;
    data["shortCut"] = this.shortCut;
    data["name"] = this.name;
    return data;
  }
}

export interface IBuildingDto {
  id?: string;
  description?: string | undefined;
  shortCut?: string | undefined;
  name?: string | undefined;
}

export class GroupDto implements IGroupDto {
  id?: string;
  description?: string | undefined;
  name?: string | undefined;

  constructor(data?: IGroupDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.description = _data["description"];
      this.name = _data["name"];
    }
  }

  static fromJS(data: any): GroupDto {
    data = typeof data === 'object' ? data : {};
    let result = new GroupDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    data["id"] = this.id;
    data["description"] = this.description;
    data["name"] = this.name;
    return data;
  }
}

export interface IGroupDto {
  id?: string;
  description?: string | undefined;
  name?: string | undefined;
}

export class LockDto implements ILockDto {
  id?: string;
  description?: string | undefined;
  serialNumber?: string | undefined;
  buildingId?: string;
  type?: LockType;
  name?: string | undefined;
  floor?: string | undefined;
  roomNumber?: string | undefined;

  constructor(data?: ILockDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.description = _data["description"];
      this.serialNumber = _data["serialNumber"];
      this.buildingId = _data["buildingId"];
      this.type = _data["type"];
      this.name = _data["name"];
      this.floor = _data["floor"];
      this.roomNumber = _data["roomNumber"];
    }
  }

  static fromJS(data: any): LockDto {
    data = typeof data === 'object' ? data : {};
    let result = new LockDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    data["id"] = this.id;
    data["description"] = this.description;
    data["serialNumber"] = this.serialNumber;
    data["buildingId"] = this.buildingId;
    data["type"] = this.type;
    data["name"] = this.name;
    data["floor"] = this.floor;
    data["roomNumber"] = this.roomNumber;
    return data;
  }
}

export interface ILockDto {
  id?: string;
  description?: string | undefined;
  serialNumber?: string | undefined;
  buildingId?: string;
  type?: LockType;
  name?: string | undefined;
  floor?: string | undefined;
  roomNumber?: string | undefined;
}

export enum LockType {
  Cylinder = 0,
  SmartHandle = 1,
}

export class MediaDto implements IMediaDto {
  id?: string;
  description?: string | undefined;
  serialNumber?: string | undefined;
  groupId?: string;
  type?: MediaType;
  owner?: string | undefined;

  constructor(data?: IMediaDto) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.description = _data["description"];
      this.serialNumber = _data["serialNumber"];
      this.groupId = _data["groupId"];
      this.type = _data["type"];
      this.owner = _data["owner"];
    }
  }

  static fromJS(data: any): MediaDto {
    data = typeof data === 'object' ? data : {};
    let result = new MediaDto();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    data["id"] = this.id;
    data["description"] = this.description;
    data["serialNumber"] = this.serialNumber;
    data["groupId"] = this.groupId;
    data["type"] = this.type;
    data["owner"] = this.owner;
    return data;
  }
}

export interface IMediaDto {
  id?: string;
  description?: string | undefined;
  serialNumber?: string | undefined;
  groupId?: string;
  type?: MediaType;
  owner?: string | undefined;
}

export enum MediaType {
  Card = 0,
  Transponder = 1,
  TransponderWithCardInlay = 2,
}

export class ApiException extends Error {
  message: string;
  status: number;
  response: string;
  headers: { [key: string]: any; };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

export class SwaggerException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any; };
  result: any;

  constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isSwaggerException = true;

  static isSwaggerException(obj: any): obj is SwaggerException {
    return obj.isSwaggerException === true;
  }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
  if (result !== null && result !== undefined)
    return _observableThrow(result);
  else
    return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
  return new Observable<string>((observer: any) => {
    if (!blob) {
      observer.next("");
      observer.complete();
    } else {
      let reader = new FileReader();
      reader.onload = event => {
        observer.next((event.target as any).result);
        observer.complete();
      };
      reader.readAsText(blob);
    }
  });
}
